/** 风格预设 — 纯数据 */
const STYLE_PRESETS = {
  light: {
    id: "light",
    name: "浅色",
    bg: "#ffffff",
    text: "#1a1a1a",
    promptBg: "#f0f4ff",
    promptBorder: "#c8d4f0",
    promptText: "#2c3e6b",
    codeBg: "#f6f8fa",
    codeText: "#24292e",
    codeBorder: "#e1e4e8",
    accent: "#4a90d9",
    fontFamily: '-apple-system, "Segoe UI", Roboto, "Noto Sans SC", sans-serif',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  dark: {
    id: "dark",
    name: "深色",
    bg: "#1e1e2e",
    text: "#cdd6f4",
    promptBg: "#313244",
    promptBorder: "#45475a",
    promptText: "#bac2de",
    codeBg: "#181825",
    codeText: "#a6e3a1",
    codeBorder: "#313244",
    accent: "#89b4fa",
    fontFamily: '-apple-system, "Segoe UI", Roboto, "Noto Sans SC", sans-serif',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  warm: {
    id: "warm",
    name: "暖色",
    bg: "#fdf6e3",
    text: "#073642",
    promptBg: "#eee8d5",
    promptBorder: "#d4c9a8",
    promptText: "#586e75",
    codeBg: "#eee8d5",
    codeText: "#586e75",
    codeBorder: "#d4c9a8",
    accent: "#b58900",
    fontFamily: 'Georgia, "Noto Serif SC", serif',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  ocean: {
    id: "ocean",
    name: "海洋",
    bg: "#0d1b2a",
    text: "#e0e1dd",
    promptBg: "#1b263b",
    promptBorder: "#415a77",
    promptText: "#a8b2c1",
    codeBg: "#0d1b2a",
    codeText: "#7ec8e3",
    codeBorder: "#1b263b",
    accent: "#7ec8e3",
    fontFamily: '-apple-system, "Segoe UI", Roboto, "Noto Sans SC", sans-serif',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  nord: {
    id: "nord",
    name: "Nord",
    bg: "#2e3440",
    text: "#eceff4",
    promptBg: "#3b4252",
    promptBorder: "#4c566a",
    promptText: "#d8dee9",
    codeBg: "#242933",
    codeText: "#a3be8c",
    codeBorder: "#4c566a",
    accent: "#88c0d0",
    fontFamily: '-apple-system, "Segoe UI", Roboto, "Noto Sans SC", sans-serif',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  solarized: {
    id: "solarized",
    name: "太阳化",
    bg: "#002b36",
    text: "#839496",
    promptBg: "#073642",
    promptBorder: "#586e75",
    promptText: "#93a1a1",
    codeBg: "#073642",
    codeText: "#859900",
    codeBorder: "#586e75",
    accent: "#268bd2",
    fontFamily: 'Consolas, "JetBrains Mono", monospace',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  dracula: {
    id: "dracula",
    name: "Dracula",
    bg: "#282a36",
    text: "#f8f8f2",
    promptBg: "#44475a",
    promptBorder: "#6272a4",
    promptText: "#bd93f9",
    codeBg: "#21222c",
    codeText: "#50fa7b",
    codeBorder: "#44475a",
    accent: "#ff79c6",
    fontFamily: '"JetBrains Mono", "Fira Code", monospace',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  monokai: {
    id: "monokai",
    name: "Monokai",
    bg: "#272822",
    text: "#f8f8f2",
    promptBg: "#3e3d32",
    promptBorder: "#75715e",
    promptText: "#a6e22e",
    codeBg: "#1e1f1c",
    codeText: "#f92672",
    codeBorder: "#75715e",
    accent: "#66d9ef",
    fontFamily: '"Consolas", "Monaco", monospace',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  github: {
    id: "github",
    name: "GitHub",
    bg: "#ffffff",
    text: "#24292e",
    promptBg: "#f6f8fa",
    promptBorder: "#e1e4e8",
    promptText: "#586069",
    codeBg: "#f6f8fa",
    codeText: "#24292e",
    codeBorder: "#e1e4e8",
    accent: "#0366d6",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  midnight: {
    id: "midnight",
    name: "午夜",
    bg: "#000000",
    text: "#e5e5e5",
    promptBg: "#1a1a1a",
    promptBorder: "#333333",
    promptText: "#a3a3a3",
    codeBg: "#0a0a0a",
    codeText: "#22c55e",
    codeBorder: "#262626",
    accent: "#ffffff",
    fontFamily: '-apple-system, "Segoe UI", sans-serif',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
  retro: {
    id: "retro",
    name: "复古",
    bg: "#f5f5dc",
    text: "#2d2d2d",
    promptBg: "#e8e8c8",
    promptBorder: "#c4c4a0",
    promptText: "#5c5c3d",
    codeBg: "#f0f0d0",
    codeText: "#8b4513",
    codeBorder: "#c4c4a0",
    accent: "#8b7355",
    fontFamily: '"Courier New", Courier, monospace',
    fontSize: "15px",
    borderRadius: "4px",
    padding: "28px",
    watermark: "AI Glance",
  },
  forest: {
    id: "forest",
    name: "森林",
    bg: "#1a2f1a",
    text: "#d4e5d4",
    promptBg: "#2d4a2d",
    promptBorder: "#4a774a",
    promptText: "#a8c8a8",
    codeBg: "#152615",
    codeText: "#90EE90",
    codeBorder: "#3d5c3d",
    accent: "#90EE90",
    fontFamily: '-apple-system, "Segoe UI", sans-serif',
    fontSize: "15px",
    borderRadius: "12px",
    padding: "28px",
    watermark: "AI Glance",
  },
};

export default STYLE_PRESETS;
